server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dialogue_db
      auto-index-creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080
          jwk-set-uri: http://auth-service:8080/oauth2/jwks

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG